import { createClient } from '@/lib/supabase/server'
import type { Category, CommentData, FeedCase, ViewerProfile, CaseDetailData } from '@/lib/types'

export async function getViewer(): Promise<ViewerProfile | null> { const supabase = await createClient(); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return null; const { data } = await supabase.from('profiles').select('id,username,display_name,avatar_url,role,reputation').eq('id', auth.user.id).maybeSingle(); return (data as ViewerProfile | null) ?? null }
export async function getCategories(): Promise<Category[]> { const supabase = await createClient(); const { data } = await supabase.from('categories').select('id,label,description,sort_order').order('sort_order', { ascending: true }); return (data as Category[] | null) ?? [] }

type FeedParams = { viewerId?: string | null; category?: string; q?: string; sort?: string; page?: number; ids?: string[]; authorId?: string }
export async function getFeedCases(params: FeedParams = {}) {
  const supabase = await createClient(); const page = Math.max(1, params.page ?? 1); const pageSize = 20
  let query = supabase.from('cases').select('id,author_id,title,summary,body,category,status,visibility,is_locked,created_at,updated_at').order('created_at', { ascending: false }).limit(250)
  if (params.category && params.category !== 'all') query = query.eq('category', params.category); if (params.ids?.length) query = query.in('id', params.ids); if (params.authorId) query = query.eq('author_id', params.authorId)
  const { data: rawCases, error } = await query; if (error || !rawCases?.length) return { items: [] as FeedCase[], hasMore: false }
  const caseIds = rawCases.map((c) => c.id); const authorIds = [...new Set(rawCases.map((c) => c.author_id))]
  const [profilesRes, categoriesRes, votesRes, commentsRes, evidenceRes, indicatorsRes] = await Promise.all([
    supabase.from('profiles').select('id,username,display_name,avatar_url,role,reputation').in('id', authorIds), supabase.from('categories').select('id,label'), supabase.from('case_votes').select('case_id,user_id,value').in('case_id', caseIds), supabase.from('comments').select('id,case_id').in('case_id', caseIds), supabase.from('case_evidence').select('id,case_id,storage_path,mime_type').in('case_id', caseIds), supabase.from('case_indicators').select('id,case_id,indicator_type,value,normalized_value').in('case_id', caseIds)
  ])
  const profiles = new Map((profilesRes.data ?? []).map((p) => [p.id, p as ViewerProfile])); const categories = new Map((categoriesRes.data ?? []).map((c) => [c.id, c.label])); const score = new Map<string, number>(); const userVote = new Map<string, -1 | 0 | 1>()
  for (const v of votesRes.data ?? []) { score.set(v.case_id, (score.get(v.case_id) ?? 0) + Number(v.value)); if (params.viewerId && v.user_id === params.viewerId) userVote.set(v.case_id, Number(v.value) as -1 | 1) }
  const commentCount = new Map<string, number>(); for (const c of commentsRes.data ?? []) commentCount.set(c.case_id, (commentCount.get(c.case_id) ?? 0) + 1)
  const evidenceCount = new Map<string, number>(); const firstImagePath = new Map<string, string>(); for (const e of evidenceRes.data ?? []) { evidenceCount.set(e.case_id, (evidenceCount.get(e.case_id) ?? 0) + 1); if (e.mime_type?.startsWith('image/') && !firstImagePath.has(e.case_id) && e.storage_path) firstImagePath.set(e.case_id, e.storage_path) }
  const evidencePreviewUrls = new Map<string, string>(); await Promise.all([...firstImagePath.entries()].map(async ([caseId, storagePath]) => { const { data } = await supabase.storage.from('evidence').createSignedUrl(storagePath, 300); if (data?.signedUrl) evidencePreviewUrls.set(caseId, data.signedUrl) }))
  const indicators = new Map<string, Array<{id:string;indicator_type:string;value:string;normalized_value:string}>>(); for (const i of indicatorsRes.data ?? []) { const list = indicators.get(i.case_id) ?? []; list.push({ id: i.id, indicator_type: i.indicator_type, value: i.value, normalized_value: i.normalized_value }); indicators.set(i.case_id, list) }
  const saved = new Set<string>(); if (params.viewerId) { const { data } = await supabase.from('saved_cases').select('case_id').eq('user_id', params.viewerId).in('case_id', caseIds); for (const s of data ?? []) saved.add(s.case_id) }
  let items: FeedCase[] = rawCases.map((c) => ({ ...c, categoryLabel: categories.get(c.category) ?? c.category, author: profiles.get(c.author_id) ?? null, score: score.get(c.id) ?? 0, commentCount: commentCount.get(c.id) ?? 0, evidenceCount: evidenceCount.get(c.id) ?? 0, evidencePreviewUrl: evidencePreviewUrls.get(c.id) ?? null, indicators: indicators.get(c.id) ?? [], userVote: userVote.get(c.id) ?? 0, saved: saved.has(c.id) }))
  const q = params.q?.trim().toLocaleLowerCase('de-DE'); if (q) items = items.filter((item) => [item.title,item.summary ?? '',item.body,item.author?.username ?? '',...item.indicators.flatMap((i) => [i.value, i.normalized_value])].join(' ').toLocaleLowerCase('de-DE').includes(q))
  if (params.sort === 'top') items.sort((a, b) => b.score - a.score || Date.parse(b.created_at) - Date.parse(a.created_at)); else if (params.sort === 'discussed') items.sort((a, b) => b.commentCount - a.commentCount || Date.parse(b.created_at) - Date.parse(a.created_at)); else items.sort((a, b) => Date.parse(b.created_at) - Date.parse(a.created_at))
  const start = (page - 1) * pageSize; return { items: items.slice(start, start + pageSize), hasMore: items.length > start + pageSize }
}

export async function getSiteStats() { const supabase = await createClient(); const today = new Date(); today.setHours(0,0,0,0); const isoToday = today.toISOString(); const [cases,comments,indicators,open,todayCases,todayComments] = await Promise.all([supabase.from('cases').select('id',{count:'exact',head:true}),supabase.from('comments').select('id',{count:'exact',head:true}),supabase.from('case_indicators').select('id',{count:'exact',head:true}),supabase.from('cases').select('id',{count:'exact',head:true}).in('status',['reported','investigating']),supabase.from('cases').select('id',{count:'exact',head:true}).gte('created_at',isoToday),supabase.from('comments').select('id',{count:'exact',head:true}).gte('created_at',isoToday)]); return { cases:cases.count??0, comments:comments.count??0, indicators:indicators.count??0, open:open.count??0, todayCases:todayCases.count??0, todayComments:todayComments.count??0 } }
export async function getViewerCommunityStats(viewerId: string) { const supabase = await createClient(); const [cases,confirmed,comments] = await Promise.all([supabase.from('cases').select('id',{count:'exact',head:true}).eq('author_id',viewerId),supabase.from('cases').select('id',{count:'exact',head:true}).eq('author_id',viewerId).eq('status','confirmed'),supabase.from('comments').select('id',{count:'exact',head:true}).eq('author_id',viewerId)]); return { cases:cases.count??0, confirmed:confirmed.count??0, comments:comments.count??0 } }
export async function getCategoryCounts(categories: Category[]) { const supabase = await createClient(); const entries = await Promise.all(categories.map(async (category)=>{ const {count}=await supabase.from('cases').select('id',{count:'exact',head:true}).eq('category',category.id); return [category.id,count??0] as const })); return Object.fromEntries(entries) as Record<string,number> }

export async function getCaseDetail(id: string, viewerId?: string | null): Promise<CaseDetailData | null> {
  const supabase = await createClient(); const { data:c,error } = await supabase.from('cases').select('id,author_id,title,summary,body,category,status,visibility,is_locked,created_at,updated_at').eq('id',id).maybeSingle(); if (error || !c) return null
  const [profileRes,categoryRes,votesRes,commentsRes,evidenceRes,indicatorsRes] = await Promise.all([supabase.from('profiles').select('id,username,display_name,avatar_url,role,reputation').eq('id',c.author_id).maybeSingle(),supabase.from('categories').select('id,label').eq('id',c.category).maybeSingle(),supabase.from('case_votes').select('user_id,value').eq('case_id',c.id),supabase.from('comments').select('id,case_id,author_id,parent_id,body,visibility,created_at,updated_at').eq('case_id',c.id).order('created_at',{ascending:true}),supabase.from('case_evidence').select('id,storage_path,mime_type,size_bytes,caption,sha256').eq('case_id',c.id).order('created_at',{ascending:true}),supabase.from('case_indicators').select('id,indicator_type,value,normalized_value').eq('case_id',c.id).order('created_at',{ascending:true})])
  const rawComments = commentsRes.data ?? []; const commentAuthorIds=[...new Set(rawComments.map((x)=>x.author_id))]; const commentIds=rawComments.map((x)=>x.id)
  const [commentProfilesRes,commentVotesRes] = await Promise.all([commentAuthorIds.length?supabase.from('profiles').select('id,username,display_name,avatar_url,role,reputation').in('id',commentAuthorIds):Promise.resolve({data:[]}),commentIds.length?supabase.from('comment_votes').select('comment_id,user_id,value').in('comment_id',commentIds):Promise.resolve({data:[]})])
  const commentProfiles=new Map((commentProfilesRes.data??[]).map((p)=>[p.id,p as ViewerProfile])); const commentScores=new Map<string,number>(); const commentUserVotes=new Map<string,-1|0|1>(); for(const v of commentVotesRes.data??[]){commentScores.set(v.comment_id,(commentScores.get(v.comment_id)??0)+Number(v.value)); if(viewerId&&v.user_id===viewerId)commentUserVotes.set(v.comment_id,Number(v.value) as -1|1)}
  const comments:CommentData[]=rawComments.map((x)=>({...x,author:commentProfiles.get(x.author_id)??null,score:commentScores.get(x.id)??0,userVote:commentUserVotes.get(x.id)??0})); let score=0; let userVote:-1|0|1=0; for(const v of votesRes.data??[]){score+=Number(v.value); if(viewerId&&v.user_id===viewerId)userVote=Number(v.value) as -1|1}
  let saved=false; if(viewerId){const {data}=await supabase.from('saved_cases').select('case_id').eq('case_id',c.id).eq('user_id',viewerId).maybeSingle(); saved=Boolean(data)}
  const evidence=await Promise.all((evidenceRes.data??[]).map(async(e)=>{const {data}=await supabase.storage.from('evidence').createSignedUrl(e.storage_path,600); return {id:e.id,caption:e.caption,mime_type:e.mime_type,size_bytes:Number(e.size_bytes),sha256:e.sha256??null,signedUrl:data?.signedUrl??null}}))
  return {...c,categoryLabel:categoryRes.data?.label??c.category,author:(profileRes.data as ViewerProfile|null)??null,score,commentCount:comments.length,evidenceCount:evidence.length,indicators:indicatorsRes.data??[],userVote,saved,evidence,comments}
}
export async function getProfileByUsername(username:string){const supabase=await createClient(); const {data}=await supabase.from('profiles').select('id,username,display_name,avatar_url,bio,role,reputation,created_at').eq('username',username).maybeSingle(); return data}
